services:
  terrakko:
    container_name: terrakko
    image: ghcr.io/nekko-lab/terrakko:main
    tty: true
    restart: unless-stopped
    volumes:
      # To use a custom CA cert for Proxmox VE, uncomment and place the cert file accordingly:
      # - ./certs/pve-ca.pem:/certs/pve-ca.pem:ro
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env

networks:
  default:
    driver: bridge
