services:
  terrakko:
    container_name: terrakko
    tty: true
    build:
      context: .
      dockerfile: 'Dockerfile'
      args:
          lang: 'C'
          dir: "${WORKDIR}"
    user: "1000:1000"
    working_dir: /home/${WORKDIR}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "${PVE_EXTRA_HOST:-placeholder:127.0.0.1}"
    volumes:
      - ./${WORKDIR}:/home/${WORKDIR}
      - ./certs:/certs:ro
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env

networks:
  default:
    driver: bridge
