services:
  terrakko:
    container_name: terrakko
    tty: true
    build:
      context: .
      dockerfile: 'Dockerfile'
      args:
          lang: 'C'
          dir: "${WORKDIR}"
    user: "1000:1000"
    working_dir: /home/${WORKDIR}
    volumes:
      - ./${WORKDIR}:/home/${WORKDIR}
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env

networks:
  default:
    driver: bridge
